services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: smart-home-server
    restart: unless-stopped
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=production
      - LIGHT_1_MAC=d8a0113a94b6
      - LIGHT_1_IP=192.168.1.17
      - LIGHT_1_PORT=38899
      - LIGHT_2_MAC=d8a0113a94ec
      - LIGHT_2_IP=192.168.1.68
      - LIGHT_2_PORT=38899
      - LIGHT_3_MAC=d8a011c3f7f5
      - LIGHT_3_IP=192.168.1.195
      - LIGHT_3_PORT=38899
      - CLAP_DETECTION_ENABLED=true
    # Use host network mode to allow UDP communication with local smart lights
    network_mode: host

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: smart-home-client
    network_mode: host
    restart: unless-stopped
    depends_on:
      - server

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: smart-home-tunnel
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    network_mode: host
    restart: unless-stopped
    depends_on:
      - client
      - server
